project_id = "gvsxentbbzuyanqbqvea"

[functions.salesforce-auth]
verify_jwt = false

[functions.salesforce-callback]
verify_jwt = false

[functions.salesforce-sync-price]
verify_jwt = false

[functions.salesforce-auto-sync]
verify_jwt = false
